/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  plugins: ["@ianvs/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
  "tailwindStylesheet": "./app/(app)/globals.css",
  "importOrder": [
    "^(react|react-dom)(/.*)?$",
    "^next(/.*)?$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/types$",
    "^@/env.*$",
    "^@/types/.*$",
    "^@/config/.*$",
    "^@/lib/.*$",
    "^@/hooks/.*$",
    "^@/components/ui/.*$",
    "^@/components/.*$",
    "^@/styles/.*$",
    "^@/app/.*$",
    "^@/utilities/.*$",
    "",
    "^[./]",
],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
}